import Foundation

// AUTO-GENERATED — non modificare manualmente. Sorgente: Config/tooling/canonical_tool_registry.json
// Rigenerare: python3 scripts/sync_tool_descriptions_swift.py
// (anche in build Xcode: fase «Sync tool_descriptions Swift» sul target CoderIDEMCPServer.)

enum RustSyncedToolDescriptions {
    /// `mcpName` coincide con `Tool.name` (es. `coderide_read`).
    static func text(mcpName: String, fallback: String) -> String {
        parsed[mcpName] ?? fallback
    }

    private static let parsed: [String: String] = {
        guard let obj = try? JSONSerialization.jsonObject(with: Data(embedded.utf8)) as? [String: String] else {
            assertionFailure("tool_descriptions embedded JSON non valido")
            return [:]
        }
        return obj
    }()

    private static let embedded = """
    {
      "coderide_activate_debug_mode": "Open or focus IDE debug workflow / instrumentation UI. Usage: optional reason string.",
      "coderide_activate_plan_mode": "Open or focus the IDE plan panel for structured multi-step planning before large edits. Usage: optional reason string explaining why plan mode is needed.",
      "coderide_audit_bug_api_contracts": "Read-only audit: API surface contracts, boundary mismatches, and unsafe assumptions across modules. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_concurrency": "Read-only audit: races, locks, actors, async boundaries, and shared mutable state risks. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_dependency_drift": "Read-only audit: dependency/version skew vs lockfiles and expected toolchain baselines. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_diff_risks": "Read-only audit: risky patterns introduced by recent diffs (focused churn analysis). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_diff_semantics": "Read-only audit: semantic behavior shifts in diffs (logic drift, unintended changes). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_error_handling": "Read-only audit: error propagation, Result/throws gaps, swallowed errors, and recovery paths. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_hotspots": "Read-only audit: complexity hotspots, churn-heavy files, and fragile regions. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_nil_crash_paths": "Read-only audit: null/optional mishandling and likely crash paths (force-unwrap, unchecked). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_state_machine": "Read-only audit: state machines, invalid transitions, and lifecycle edge cases. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_test_gaps": "Read-only audit: missing or shallow tests for critical logic and regressions. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_bug_test_impact": "Read-only audit: test coverage vs recent changes; tests that should exist for touched code. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_correlate_findings": "Read-only audit helper: correlate multiple findings into clusters/themes (meta-analysis). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_explain_finding": "Read-only audit helper: produce a structured explanation for one audit finding. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_run_profile": "Execute a named read-only audit profile bundle (host-defined grouping of checks). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_authz": "Read-only security audit: authorization, access control, privilege checks, and IDOR patterns. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_crypto": "Read-only security audit: cryptography misuse, weak algorithms, and secret handling in code. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_dataflow": "Read-only security audit: sensitive data flow, logging leaks, and exfiltration patterns. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_dependencies": "Read-only security audit: vulnerable or suspicious dependency usage and supply signals. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_deserialization": "Read-only security audit: deserialization boundaries and injection/unsafe object graphs. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_patterns": "Read-only security audit: OWASP-style pattern scan (SQLi, XSS hooks, command injection shapes). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_secrets": "Read-only security audit: hard-coded secrets, tokens, keys, and unsafe credential patterns. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_supply_chain": "Read-only security audit: supply-chain and third-party risk surfacing in the workspace. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_security_surface": "Read-only security audit: attack surface expansion (new endpoints, parsers, IPC). Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_verify_bundle": "Read-only audit: validate a prior audit bundle/export for consistency and completeness. Usage: optional path, scope_files or scopeFiles (JSON array or CSV), file, profile, message, line, evidence — narrow the scope for faster, focused read-only audits.",
      "coderide_audit_perf_bottlenecks": "Read-only performance audit: detect bottlenecks such as blocking calls, synchronous main-thread work, and expensive loops. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_memory": "Read-only performance audit: detect memory issues such as retain cycles, strong self captures, and cache misuse. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_ui_responsiveness": "Read-only performance audit: detect UI responsiveness issues such as main-thread blocking, heavy onAppear, and synchronous I/O in UI code. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_startup": "Read-only performance audit: detect startup-time issues such as +load methods, constructors, and eager initialization. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_hot_paths": "Read-only performance audit: detect hot paths via git churn analysis, nested loops, and file complexity indicators. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_correlate": "Read-only performance audit helper: correlate multiple perf findings into compound hotspots and shared clusters. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_audit_perf_trending": "Read-only performance audit helper: compare current perf findings with baseline trends and surface regressions. Usage: optional path, scope_files or scopeFiles (JSON array or CSV).",
      "coderide_bughunter_autofix_apply": "Apply autofix for top verified finding. Usage: run_id (required); optional conversation_id.",
      "coderide_bughunter_autofix_commit": "Apply+commit autofix and queue follow-up review. Usage: run_id (required); optional conversation_id.",
      "coderide_bughunter_autofix_preview": "Preview autofix for top verified BugHunter finding. Usage: run_id (required); optional conversation_id.",
      "coderide_bughunter_cancel_run": "Stop an in-flight BugHunter run. Usage: run_id (required); optional conversation_id.",
      "coderide_bughunter_commit_window": "Run BugHunter on a commit plus correlated history. Usage: git_root, primary_commit (required); optional conversation_id.",
      "coderide_bughunter_explain_cluster": "Explain strongest correlated defect cluster. Usage: run_id (required); optional conversation_id.",
      "coderide_bughunter_findings": "List BugHunter-linked findings through review. Usage: run_id; optional kind/severity/status/conversation_id.",
      "coderide_bughunter_install_hook": "Install managed post-commit BugHunter hook. Usage: git_root (required).",
      "coderide_bughunter_run_history": "List prior BugHunter runs with summaries. Usage: optional conversation_id.",
      "coderide_bughunter_start": "Start BugHunter over uncommitted commits/commit windows/branch windows. Usage: source_kind, git_root plus primary_commit/branch fields as required by kind; optional conversation_id.",
      "coderide_bughunter_status": "Poll BugHunter run + linked review status. Usage: run_id; optional conversation_id.",
      "coderide_bughunter_uninstall_hook": "Remove managed BugHunter hook. Usage: git_root (required).",
      "coderide_codebase_search": "Index-backed symbol search by name/pattern/kind (faster than grep for definitions). Usage: query; optional kind, filePattern/path (query stem); pathScope or target_directories to limit directory scope (path is not a scope key here).",
      "coderide_create_file": "Atomically create a new file; fails if the path already exists. Usage: path and full content.",
      "coderide_diagnostics": "Run a full diagnostic/build pass and return structured errors/warnings. Usage: optional manager string if the host supports it; slower than read_lints.",
      "coderide_export_debug_bundle": "Zip SoloCode AgentDebug NDJSON traces into a shareable .solocode bundle. Usage: optional workspace_roots CSV for multi-root fingerprint alignment.",
      "coderide_debug_clean": "Remove tracked debug markers or instrumentation from files or the workspace. Usage: optional path, type, dry_run, hypothesis_id.",
      "coderide_debug_context": "Gather debug context for the current workspace, such as git status, diagnostics, and environment clues. Usage: optional scope, include_file_content, max_depth.",
      "coderide_debug_hypothesize": "Propose or update a structured debugging hypothesis with evidence and confidence. Usage: action (required); optional hypothesis_id, title, description, status, evidence, confidence, root_cause_type, related_files, related_tests.",
      "coderide_debug_instrument": "Insert executable debug instrumentation into source code at a precise location. Usage: path, line, type, expression (required); optional condition, hypothesis_id, label.",
      "coderide_debug_log": "Write structured entries to the debug log for the current investigation. Usage: message (required); optional severity, source, detail, category, run_id, hypothesis_id, data.",
      "coderide_debug_mark": "Insert a tagged debug marker or helper snippet into a file for later cleanup. Usage: path, line, comment (required); optional code, type, expression, hypothesis_id.",
      "coderide_debug_query": "Query structured debug log entries by text or metadata. Usage: optional severity, category, source, search, tags, hypothesis_id, time_range, session_id, group_by, format, limit, offset.",
      "coderide_debug_request_user": "Queue a user-facing request in the debug workflow, such as a question, repro step, or fix confirmation. Usage: kind, prompt (required).",
      "coderide_debug_resolve": "Resolve the current debug session with a final summary. Usage: summary (required).",
      "coderide_debug_session": "Manage the lifecycle of a debug session, including start, snapshot/export, and stop. Usage: action (required); optional label.",
      "coderide_debug_set_phase": "Set the current debug workflow phase for the active investigation. Usage: phase (required); optional detail.",
      "coderide_debug_snapshot": "Capture, compare, or list snapshots of the current debug session state. Usage: action (required); optional label, compare_with.",
      "coderide_debug_test_check": "Run targeted verification checks for a debug fix in the workspace. Usage: scope (required); optional path, filter, hypothesis_id, timeout_ms.",
      "coderide_debug_timeline": "Build a chronological view of debug events for the current session. Usage: optional filter, time_range, hypothesis_id, format.",
      "coderide_debug_trace_analyze": "Analyze raw error text, crash output, or stack traces into actionable debug findings. Usage: error_text (required); optional error_type, context.",
      "coderide_file_outline": "Structural outline (symbols/sections) for one file. Usage: path.",
      "coderide_find_files": "Fuzzy / index-backed file discovery by name. Usage: query or pattern; optional path, pathScope, target_directories (comma-separated; first used as search root), filePattern, extension.",
      "coderide_find_references": "List usages before refactors. Usage: query or name for the symbol; optional path, pathScope, or target_directories to limit search directory.",
      "coderide_find_symbol": "Locate symbol definitions (types, functions, methods). Usage: query or name; optional kind filter; optional path, pathScope, or target_directories to limit search directory.",
      "coderide_git_diff": "Show working-tree or scoped diff. Usage: optional path; optional staged hint when supported.",
      "coderide_glob": "Find paths matching a glob (e.g. **/*.swift). Usage: pattern; optional path, pathScope, or target_directories (comma-separated; first segment used as root).",
      "coderide_grep": "Ripgrep-style content search (regex, filters, context lines). Usage: query or pattern; optional path/pathScope, fileType, glob, context_lines, case_sensitive, multiline, output_mode.",
      "coderide_list_dir": "List files and subdirectories under a path (directory discovery). Usage: path to the folder to enumerate.",
      "coderide_mermaid_render": "Render Mermaid in the IDE (architecture/flow visualization). Usage: code (required); optional title.",
      "coderide_plan_create": "Create/replace the visible IDE plan snapshot. Usage: goal (required); optional steps JSON, chosen_path, conversation_id, replace_existing.",
      "coderide_plan_diff": "Compare two plan snapshots (what changed between rounds). Usage: from_snapshot_id (required); optional to_snapshot_id, conversation_id.",
      "coderide_plan_history_read": "Read historical plan snapshots. Usage: optional conversation_id, limit.",
      "coderide_plan_read": "Fetch latest plan snapshot. Usage: optional conversation_id, include_history, history_limit.",
      "coderide_plan_request_user_input": "Block plan flow on structured clarification questions in the IDE. Usage: questions JSON (required); optional title, phase, round, context, conversation_id.",
      "coderide_plan_set_walkthrough": "Store final walkthrough markdown and outcome for the plan. Usage: markdown (required); optional summary, outcome, conversation_id.",
      "coderide_plan_step_batch_update": "Apply many step updates in one call. Usage: updates JSON array; optional conversation_id.",
      "coderide_plan_step_dependency_set": "Set prerequisites for a step. Usage: step_id, depends_on JSON array; optional conversation_id.",
      "coderide_plan_step_reorder": "Reorder steps. Usage: ordered_step_ids JSON array; optional conversation_id.",
      "coderide_plan_step_update": "Lightweight step status/title update while executing the plan in the IDE. Usage: step_id and status (required); optional title.",
      "coderide_plan_step_upsert": "Create/update one plan step with metadata. Usage: step_id and status (required); optional title, description, target_file, linked_files, depends_on, notes, conversation_id.",
      "coderide_policy_ack": "Acknowledge a repository policy hash before mutating tools when the host requires it. Usage: hash (required).",
      "coderide_read": "Read a file from the workspace with line numbers. Always read before editing. Usage: path (required). Optional offset/limit as line hints when supported by the host.",
      "coderide_read_lints": "Read current linter/IDE diagnostics without a full build when available. Usage: optional path filter, severity, limit.",
      "coderide_read_range": "Read an inclusive line slice from a file (faster than whole file for large sources). Usage: path; start and end as start_line/end_line or start/end integers when available.",
      "coderide_regex_replace": "Regex-powered single-file replace (capture groups in replacement). Usage: path, pattern, replacement; optional flags (e.g. i for case-insensitive), replace_all (default false replaces one match).",
      "coderide_review_apply_fix": "Apply an IDE-suggested fix for a finding. Usage: finding identifiers per host schema (finding_id, session_id, etc.).",
      "coderide_review_apply_patch": "Apply the verified patch to the workspace. The host runs build checks, targeted tests, regression audit, then the full Xcode scheme test suite (all test bundles in the scheme—not only files touched). Any failing tests must be fixed before considering the fix complete; do not ignore unrelated failures. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_close_finding": "Close a finding after fix or explicit resolution. Usage: finding_id, session_id; optional reason; optional conversation_id.",
      "coderide_review_comment": "Attach analyst comment or metadata to a finding/session. Usage: fields per host schema.",
      "coderide_review_configure": "Adjust live review settings (workers, rounds, toggles). Usage: fields per host schema.",
      "coderide_review_diff_summary": "Summarize diffs associated with the review scope (read-only). Usage: session identifiers as required.",
      "coderide_review_dismiss": "Dismiss a finding with rationale. Usage: finding_id/session_id plus dismiss fields per host.",
      "coderide_review_findings": "Filter/list findings (severity, file, status, origin). Usage: optional filters; session_id/conversation_id if needed.",
      "coderide_review_get_outcome": "Fetch structured outcome summary for a session. Usage: session_id (required); optional conversation_id.",
      "coderide_review_list_sessions": "Enumerate review sessions (including finished). Usage: optional conversation_id.",
      "coderide_review_merge_pr": "Merge the PR for a finding when policy allows. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_open_pr": "Open a PR for the finding’s patch branch. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_prepare_patch": "Materialize a patch plan for a verified finding. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_preview_patch": "Read-only view of the generated patch artifact. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_resolve_conflicts": "Attempt safe conflict resolution on the review branch. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_revalidate_finding": "Re-run validation after patch application (same gates as apply: including full scheme tests when the host supports it). Fix every failing test surfaced—regressions outside the original finding are blocking. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_rollback_patch": "Undo an applied patch when rollback metadata exists. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_start": "Start a code review session over uncommitted/staged/or-against-ref scope. Usage: scope/ref and backends as needed; optional session_id/conversation_id.",
      "coderide_review_status": "Poll phase/workers/round status for the active review. Usage: optional session_id/conversation_id when multiple sessions exist.",
      "coderide_review_verify_finding": "Verify/promote a candidate finding before patching. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_review_verify_patch": "Validate patch before apply (checks / dry-run). After a real apply, failures in any project test are in scope for follow-up fixes. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_run_tests": "Run tests (cargo/swift test/xcodebuild when applicable). Usage: optional filter; optional scheme for Xcode.",
      "coderide_security_apply_patch": "Apply verified security patch; host validation includes full scheme tests when enabled—fix all failing tests, not only security-scoped ones. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_close_finding": "Close or reject a security finding with reason. Usage: finding_id, session_id; optional reason; optional conversation_id.",
      "coderide_security_findings": "List security findings (verified/candidate). Usage: session_id; optional filters kind/severity/status/conversation_id.",
      "coderide_security_prepare_patch": "Prepare patch for verified security finding. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_preview_patch": "Preview stored security patch (read-only). Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_revalidate_finding": "Post-fix security revalidation. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_rollback_patch": "Rollback applied security patch. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_start": "Start a security-hardened review session (shared VerifiedFindings backend). Usage: scope/ref; optional session_id/conversation_id.",
      "coderide_security_status": "Read security gate/session status. Usage: session_id when needed; optional conversation_id.",
      "coderide_security_verify_finding": "Promote/verify a security finding before patching. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_security_verify_patch": "Validate security patch. Usage: finding_id and session_id (required); optional conversation_id.",
      "coderide_semantic_search": "Meaning-first code search (natural language) with optional directory scoping. Usage: query; optional target_directories (comma-separated, sandboxed), pathScope/path, num_results/limit.",
      "coderide_show_swarm_panel": "Reveal swarm/multi-agent UI. Usage: optional swarm_id.",
      "coderide_show_task_panel": "Reveal IDE task/activity UI. Usage: typically empty args.",
      "coderide_skill": "Execute a local SKILL.md workflow from user skill dirs. Usage: skill or name; task or args describing the work—prefer this when a skill matches the request.",
      "coderide_str_replace": "Surgical edit: replace exactly one occurrence of old_string with new_string. Usage: path, old_string, new_string. old_string must match exactly; add context if it is not unique.",
      "coderide_subagent_bugHunter": "Spawn regression/crash-hunting specialist subagent. Usage: task (required).",
      "coderide_subagent_coder": "Spawn an editing subagent for isolated implementation work. Usage: task (required).",
      "coderide_subagent_debugger": "Spawn a debugger subagent for bug investigation and fix execution. Usage: task (required).",
      "coderide_subagent_docWriter": "Spawn documentation-focused subagent. Usage: task (required).",
      "coderide_subagent_explorer": "Spawn a read-only explorer subagent for parallel investigation. Usage: task (required) describing what to map/read.",
      "coderide_subagent_reviewer": "Spawn a reviewer subagent (quality/safety read-only review). Usage: task (required).",
      "coderide_subagent_securityAuditor": "Spawn security audit subagent. Usage: task (required).",
      "coderide_subagent_testWriter": "Spawn a tests-and-verification subagent. Usage: task (required).",
      "coderide_todo_read": "Read the shared IDE todo list / LiveCard items. Usage: no required fields.",
      "coderide_todo_write": "Update structured todos shown in the IDE. Usage: pass todos JSON batch and/or single-item fields title, status, priority, notes, activeForm, linkedFiles.",
      "coderide_web_fetch": "Fetch public URL and return Markdown content. Usage: url (required).",
      "coderide_web_search": "Internet search for up-to-date docs, APIs, CVEs, releases. Usage: query (required); optional explanation/maxResults.",
      "coderide_write": "Overwrite or create a file with full contents. Usage: path and content. Prefer coderide_str_replace for small edits to existing files."
    }
    """
}
